// <auto-generated />
using AircraftMRO.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AircraftMRO.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AircraftMroDbContext))]
    [Migration("20260820224910_RemoveCreatorSystemFeature")]
    partial class RemoveCreatorSystemFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AircraftMRO.Infrastructure.Persistence.SystemFeatureRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ControllerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("StatusText")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SystemFeatures", null, t =>
                        {
                            t.HasCheckConstraint("CK_SystemFeatures_Destination_Complete", "([ControllerName] IS NULL AND [ActionName] IS NULL) OR ([ControllerName] IS NOT NULL AND [ActionName] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SystemFeatures_DisplayOrder_NonNegative", "[DisplayOrder] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "aircraft",
                            Description = "Manage aircraft profiles, registration details, fleet status, and technical records.",
                            DisplayOrder = 10,
                            IconKey = "aircraft",
                            IsVisible = true,
                            StatusText = "Coming soon",
                            Title = "Aircraft"
                        },
                        new
                        {
                            Id = 2,
                            Code = "work-orders",
                            Description = "Plan, assign, and track maintenance work from discovery through release to service.",
                            DisplayOrder = 20,
                            IconKey = "work-order",
                            IsVisible = true,
                            StatusText = "Coming soon",
                            Title = "Work Orders"
                        },
                        new
                        {
                            Id = 3,
                            Code = "maintenance-planning",
                            Description = "Coordinate scheduled tasks, due dates, labor, tooling, and material requirements.",
                            DisplayOrder = 30,
                            IconKey = "maintenance",
                            IsVisible = true,
                            StatusText = "Coming soon",
                            Title = "Maintenance Planning"
                        },
                        new
                        {
                            Id = 4,
                            Code = "compliance-records",
                            Description = "Keep maintenance history, airworthiness evidence, and audit-ready records together.",
                            DisplayOrder = 40,
                            IconKey = "compliance",
                            IsVisible = true,
                            StatusText = "Coming soon",
                            Title = "Compliance & Records"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
